GET http://localhost:8266/api/


### auth - register new user
POST http://localhost:8266/api/auth/register
Content-Type: application/json

{
    "password": "123456",
    "fullName": "member13",
    "studentCode": "0013",
    "phoneNumber":"0013",
    "email": "member13@gmail.com"
}

###  auth -  login
POST http://localhost:8266/api/auth/login
Content-Type: application/json

{
    "password": "123456",
    "email": "admin@hcmut.edu.vn"
}


###  auth -  logout
POST http://localhost:8266/api/auth/password
Content-Type: application/json

{
    "newPassword": "1234567"
}

###  auth -  logout
POST http://localhost:8266/api/auth/logout

### item - get all of items
GET http://localhost:8266/api/item/

### item - get item by id
GET http://localhost:8266/api/item/6290b766372ca2ed6ff00c8c

### item - add new item 
POST http://localhost:8266/api/item
Content-Type: application/json

{
    "name" : "item10",
    "quantity" : "99",
    "category" : "aaaa",
    "description" : "hello world"
}

### item - update item by id
PATCH http://localhost:8266/api/item/6290b766372ca2ed6ff00c8c
Content-Type: application/json

{
    "category" : "bc"
}

### item - delete item by id
DELETE http://localhost:8266/api/item/628f3d17d4d47d5dab57be3f
Content-Type: application/json

{
    "adminPassword": "123456"
}

### user - get all of users
GET http://localhost:8266/api/user/

### user - get user by id
GET http://localhost:8266/api/user/6290976c0591c3ff4bac225f

### user - toggle enable permission
PATCH http://localhost:8266/api/user/629097230591c3ff4bac2251?togglePermission=enable

### user - toggle admin permission admin
PATCH http://localhost:8266/api/user/629097230591c3ff4bac2251?togglePermission=admin

### user - toggle fail
PATCH http://localhost:8266/api/user/628e5e98cac47ecceb92e2d8?togglePermission=f


###  auth -  login
POST http://localhost:8266/api/auth/login
Content-Type: application/json

{
    "password": "123456",
    "email": "admin@hcmut.edu.vn"
}
### user - update
PATCH http://localhost:8266/api/user/62c8eb8af1d3d00e0afd3340
Content-Type: application/json

{
    "fullName": "Tan Le",
    "studentCode": "2014453",
    "phoneNumber": "0337229811",
    "email": "tanle@hcmut.edu.vn",
    "password": "123456",
    "adminPassword": "123456"
}


### user - delete user by id
DELETE http://localhost:8266/api/user/62a4a0f427cf24e74b7e15ac


### order - get all of order
GET http://localhost:8266/api/order/


### order - get order by id
GET http://localhost:8266/api/order/629864ec6bac7b8340bce3d8

### order - create new order 
POST http://localhost:8266/api/order/
Content-Type: application/json

{
    "quantity": "5",
    "idItem": "6290b766372ca2ed6ff00c8c",
    "returnDate": "2022-12-30"
}


### order - update state of order
PATCH http://localhost:8266/api/order/6290bbc299aa53690473526c?action=confirm

### order - delete order by id
DELETE http://localhost:8266/api/order/62a4931c27cf24e74b7e144a

###  auth -  login
POST http://localhost:8266/api/auth/login
Content-Type: application/json

{
    "password": "123456",
    "email": "tan.letan8266@hcmut.edu.vn"
}